#brokerIP1=127.0.0.1
##DLeger
#enableDLegerCommitLog=true
#dLegerGroup=broker-DLeger
#dLegerPeers=d0-127.0.0.1:40911;d1-127.0.0.1:40912;d2-127.0.0.1:40913
#sendMessageThreadPoolNums=4
#dLegerSelfId=d1

brokerClusterName = RaftCluster
brokerName=RaftNode
listenPort=30912
#namesrvAddr=host.docker.internal:9876
storePathRootDir=/tmp/rmqstore/node01
storePathCommitLog=/tmp/rmqstore/node01/commitlog
enableDLegerCommitLog=true
dLegerGroup=DLegerGroup
dLegerPeers=n0-host.docker.internal:40911;n1-host.docker.internal:40912;n2-host.docker.internal:40913
## must be unique
dLegerSelfId=n1
sendMessageThreadPoolNums=4

#ACL 2.0
# 启用认证
authenticationEnabled=true
# 开启授权
authorizationEnabled=true
# 指定 ACL 配置文件路径 (容器内路径)
aclConfigPath=/opt/rocketmq/conf/plain_acl.yml

# 必须开启，否则 Proxy 内部同步可能失败
autoCreateTopicEnable=true