plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'maven-publish'
}

group = 'com.ylli'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(17)
//    }
}

repositories {
    mavenCentral()

    maven {
        url "http://127.0.0.1:18081/repository/maven-public/"
        credentials {
            username 'admin'
            password 'Guyuefangyuan6'
        }
        allowInsecureProtocol = true
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    //Spring Boot
//    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis-reactive'

    // Spring Cloud
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

    // Alibaba Cloud
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'

    // Database
    implementation 'com.mysql:mysql-connector-j'
//    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    implementation 'com.github.pagehelper:pagehelper-spring-boot-starter:2.1.0'
    implementation 'io.mybatis:mybatis-mapper:2.2.1'

    // Tools
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    // nacos 使用yaml 格式时需要使用.
    implementation 'org.yaml:snakeyaml:2.4'

    // MQ & Distributed
    implementation 'org.apache.rocketmq:rocketmq-client-java:5.2.0'
    implementation 'org.apache.seata:seata-spring-boot-starter:2.6.0'
    implementation 'org.apache.shardingsphere:shardingsphere-jdbc:5.5.2'
    implementation 'org.apache.shardingsphere:shardingsphere-transaction-base-seata-at:5.5.2'

    // Security
    implementation 'com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.5'

    // Internal
    implementation 'com.ylli:common:0.0.6'
}

tasks.named('test') {
    useJUnitPlatform()
}

dependencies {
    // https://mvnrepository.com/artifact/com.alibaba.csp/sentinel-core
    implementation 'com.alibaba.csp:sentinel-core:1.8.8'

    // sentinel dashboard
    implementation 'com.alibaba.csp:sentinel-transport-simple-http:1.8.8'
}


ext {
    set('springCloudVersion', "2025.1.1")
    set('springCloudAlibabaVersion', "2025.1.0.0")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:${springCloudAlibabaVersion}"
    }
}