# frpc.toml
serverAddr = "124.70.186.54"
serverPort = 7000

# 安全认证配置
auth.method = "token"
auth.token = "bYoqT51-"

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"    
webServer.password = "admin"

[[proxies]]             # 自定义服务名称
name = "nexus"
type = "tcp"             # 协议类型（支持 tcp/udp/http/https）
localIp = "host.docker.internal"  # 宿主机地址（Docker 特殊 DNS）
localPort = 8081         # nexus 服务端口
remotePort = 8081
#customDomains = ["124.70.186.54"]  # 可选：绑定域名（需解析到云服务器 IP

[[proxies]]             # 自定义服务名称
name = "rocketmq-proxy"
type = "tcp"             # 协议类型（支持 tcp/udp/http/https）
localIp = "host.docker.internal"  # 宿主机地址（Docker 特殊 DNS）
localPort = 18081         #  proxy 服务端口
remotePort = 18081