services:
  frpc:
    image: snowdreamtech/frpc:0.65
    container_name: frpc
#    restart: always
    ports:
      # web ui
      - "127.0.0.1:7400:7400"
      - "3389:3389"
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml