# frps_server.yml
services:
  frps:
    image: snowdreamtech/frps:0.65
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
    ports:
      - "7000:7000"
      #- "80:80"
      # web ui
      - "7500:7500"
      - "3389:3389"
    restart: always