#brokerIP1=127.0.0.1
##DLeger
#enableDLegerCommitLog=true
#dLegerGroup=broker-DLeger
#dLegerPeers=d0-127.0.0.1:40911;d1-127.0.0.1:40912;d2-127.0.0.1:40913
#sendMessageThreadPoolNums=4
#dLegerSelfId=d0

brokerClusterName = RaftCluster
brokerName=RaftNode
listenPort=30911
#namesrvAddr=host.docker.internal:9876
storePathRootDir=/tmp/rmqstore/node00
storePathCommitLog=/tmp/rmqstore/node00/commitlog
enableDLegerCommitLog=true
dLegerGroup=DLegerGroup
dLegerPeers=n0-host.docker.internal:40911;n1-host.docker.internal:40912;n2-host.docker.internal:40913
## must be unique
dLegerSelfId=n0
sendMessageThreadPoolNums=4