#brokerIP1=127.0.0.1
##DLeger
#enableDLegerCommitLog=true
#dLegerGroup=broker-DLeger
#dLegerPeers=d0-127.0.0.1:40911;d1-127.0.0.1:40912;d2-127.0.0.1:40913
#sendMessageThreadPoolNums=4
#dLegerSelfId=d2

brokerClusterName = RaftCluster
brokerName=RaftNode
listenPort=30913
#namesrvAddr=host.docker.internal:9876
storePathRootDir=/tmp/rmqstore/node02
storePathCommitLog=/tmp/rmqstore/node02/commitlog
enableDLegerCommitLog=true
dLegerGroup=DLegerGroup
dLegerPeers=n0-broker-1:40911;n1-broker-2:40912;n2-broker-3:40913
## must be unique
dLegerSelfId=n2
sendMessageThreadPoolNums=4

# 启用认证
# Broker只作为元数据提供者，不处理客户端认证授权
authenticationEnabled = false
authorizationEnabled = false

# 配置元数据提供者
authenticationMetadataProvider = org.apache.rocketmq.auth.authentication.provider.LocalAuthenticationMetadataProvider
authorizationMetadataProvider = org.apache.rocketmq.auth.authorization.provider.LocalAuthorizationMetadataProvider

# 初始化管理员用户
initAuthenticationUser = {"username":"rocketmq","password":"12345678"}