
port 6372

bind 0.0.0.0

appendonly yes

protected-mode no

#enable cluster mode
cluster-enabled yes

#ms
cluster-node-timeout 15000

#集群内配置文件
cluster-config-file "nodes-2.conf"

#公网选服务器ip,内网查看ifconfig eh0 ip4地址
cluster-announce-ip 172.30.85.191
cluster-announce-port 6372
cluster-announce-bus-port 16372
