
port 6375

bind 0.0.0.0

appendonly yes

protected-mode no

#enable cluster mode
cluster-enabled yes

#ms
cluster-node-timeout 15000

#集群内配置文件
cluster-config-file "nodes-5.conf"

#公网选服务器ip,内网查看ifconfig eh0 ip4地址
cluster-announce-ip 10.7.4.169
cluster-announce-port 6375
cluster-announce-bus-port 16375
