services:
  elasticsearch:
    image: elasticsearch:8.14.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1GB
    networks:
      - elastic
    
  logstash:
    image: logstash:8.14.3
    container_name: logstash
    ports:
      - 4560:4560
    volumes:
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash-sb.conf:/usr/share/logstash/config/logstash-sb.conf
      - ./http_ca.crt:/usr/share/logstash/config/certs/http_ca.crt
    depends_on:
      - elasticsearch
    networks:
      - elastic
    
  kibana:
    image: kibana:8.14.3
    container_name: kibana
    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - I18N_LOCALE=zh-CN
    ports:
      - 5601:5601 
    depends_on:
      - elasticsearch
    networks:
      - elastic
      
networks:
  elastic:
    external: true