#version: '20.10.24'

# semi sync 复制
services:
  salve1:
    image: mysql:8.0.32
    command: mysqld --server-id=101 --log-bin=slave-bin --binlog-format=row --innodb_flush_log_at_trx_commit=1 --relay-log=slave-relay-bin --read-only=1 --gtid_mode=on --enforce_gtid_consistency=on --expire_logs_days=7
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mysql_mgr
      
  salve2:
    image: mysql:8.0.32
    command: mysqld --server-id=102 --log-bin=slave-bin --binlog-format=row --innodb_flush_log_at_trx_commit=1 --relay-log=slave-relay-bin --read-only=1 --gtid_mode=on --enforce_gtid_consistency=on --expire_logs_days=7
    ports:
      - 23307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mysql_mgr
      
networks:
  mysql_mgr:
    external: true

