# v7
input {
 tcp {
   mode => "server"
   host => "0.0.0.0"
   port => 4560
   codec => json_lines
 }
}
output {
 stdout{
      codec => rubydebug
   }
 elasticsearch {
   hosts => ["http://elasticsearch:9200"]
#    user => "elastic"
#    password => "yPhxGjZ0qgmll*SDPgPc"
   index => "springboot-logstash-%{+YYYY.MM.dd}"
 }
}

# input {
#   tcp {
#     mode => "server"
#     host => "0.0.0.0"
#     port => 4560
#     codec => json_lines
#   }
# }
# output {
#   stdout{
#        codec => rubydebug
#     }
#   elasticsearch {
#     hosts => ["http://172.30.85.191:9200/"]
# #    ssl => true
# #    cacert => '/usr/share/logstash/config/certs/http_ca.crt'
#     ssl_verification_mode => "none"
#     user => "elastic"
#     password => "bfrW=80GC=i4BFAUNaYS"
#     index => "springboot-logstash-%{+YYYY.MM.dd}"
#   }
# }
